SET TERM ^ ;
CREATE TRIGGER FIRST_TABLE_TR FOR FIRST_TABLE 
ACTIVE
BEFORE INSERT POSITION 0
as
begin
if (new.ID_FIRST_TABLE is null) then
new.ID_FIRST_TABLE = gen_id(FIRST_TABLE_GEN,1);
end^
SET TERM ; ^
